version: '3'

services:
  pg-backend:
    image: postgres
    container_name: pg-backend
    environment:
      - POSTGRES_PASSWORD=backendvotos123
    ports:
      - "5432:5432"
    volumes:
      - C:/JavaTests/votos:/var/lib/postgresql/data
    networks:
      - postgres-network

  back-end-app:
    image: spring-app
    container_name: backend-server
    depends_on:
      - pg-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-backend:5432/postgres
      - SPRING_DATASOURCE_PASSWORD=backendvotos123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    networks:
      - postgres-network
    ports:
      - "8080:8080"
  teste-pgadmin:
    image: dpage/pgadmin4
    container_name: teste-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=backendvotos@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=backendvotos123
    ports:
      - "15432:80"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge